export const ProductsData = [
    {
      id: "1",
      title: "Classic T-Shirt",
      description: "Soft and comfortable cotton t-shirt available in various colors.",
      img: "/images/men-clothing/t-shirts-1 (1).png",
      category: "T-Shirts",
      rating: 4.5,
      price: "$15.99",
      priceWas: "$19.99",
      color: "White",
      aosDelay: 100,
    },
    {
      id: "2",
      title: "Graphic T-Shirt",
      description: "Trendy graphic t-shirt with cool designs for casual wear.",
      img: "/images/men-clothing/t-shirts-2 (2).png",
      category: "T-Shirts",
      rating: 4.7,
      price: "$18.49",
      priceWas: "", // New Arrival
      color: "Black",
      aosDelay: 200,
    },
    {
      id:"3",
      title: "Denim Jeans",
      description: "Premium quality denim jeans for a stylish look.",
      img: "/images/men-clothing/denim-bottom (2).png",
      category: "Bottom Denim",
      rating: 4.6,
      price: "$39.99",
      priceWas: "$49.99",
      color: "Blue",
      aosDelay: 300,
    },
    {
      id: "4",
      title: "Ripped Jeans",
      description: "Fashionable ripped denim jeans for modern style enthusiasts.",
      img: "/images/men-clothing/denim-bottom (1).png",
      category: "Bottom Denim",
      rating: 4.8,
      price: "$42.99",
      priceWas: "", // New Arrival
      color: "Dark Blue",
      aosDelay: 400,
    },
    {
      id: "5",
      title: "Full-Sleeve Shirt",
      description: "Elegant full-sleeve shirt, perfect for formal or casual occasions.",
      img: "/images/men-clothing/full-sleeve-shirt-2.png",
      category: "Fullsleeve Shirts",
      rating: 4.7,
      price: "$29.99",
      priceWas: "$35.99",
      color: "Light Blue",
      aosDelay: 500,
    },
    {
      id: "6",
      title: "Men's Digital Watch",
      description: "Stylish and durable digital watch for men.",
      img: "/images/men-watches/watch-2-(1).jpg",
      category: "Men's Watches",
      rating: 4.9,
      price: "$99.99",
      priceWas: "$129.99",
      color: "Black",
      aosDelay: 600,
    },
    {
      id: "7",
      title: "Women's Luxury Watch",
      description: "Elegant and chic luxury watch for women.",
      img: "/images/women-watches/watch-2-(2).jpg",
      category: "Women's Watches",
      rating: 4.8,
      price: "$119.99",
      priceWas: "",
      color: "Rose Gold",
      aosDelay: 700,
    },
    {
      id: "8",
      title: "Casual T-Shirt",
      description: "Everyday casual t-shirt for relaxed style.",
      img: "/images/men-clothing/t-shirts-2 (4).png",
      category: "T-Shirts",
      rating: 4.4,
      price: "$12.99",
      priceWas: "$14.99",
      color: "Gray",
      aosDelay: 800,
    },
    {
      id: "9",
      title: "Formal Shirt",
      description: "Perfectly tailored formal shirt for office wear.",
      img: "/images/men-clothing/full-sleeve-shirt.png",
      category: "Fullsleeve Shirts",
      rating: 4.6,
      price: "$34.99",
      priceWas: "",
      color: "White",
      aosDelay: 900,
    },
    {
      id: "10",
      title: "Classic Denim Short",
      description: "Timeless denim shorts for all seasons.",
      img: "/images/men-clothing/denim-bottom (3).png",
      category: "Bottom Denim",
      rating: 4.9,
      price: "$59.99",
      priceWas: "$79.99",
      color: "Blue",
      aosDelay: 1000,
    },
    {
        id: "11",
        title: "Sports Watch",
        description: "Durable sports watch for outdoor enthusiasts.",
        img: "/images/men-watches/watch-2-(2).jpg",
        category: "Men's Watches",
        rating: 4.7,
        price: "$89.99",
        priceWas: "$109.99",
        color: "Silver",
        aosDelay: 1100,
      },
      {
        id: "12",
        title: "Fashion Bracelet",
        description: "Beautiful bracelet to complement any outfit.",
        img: "/images/accessories/bracelet3.jpg",
        category: "Accessories",
        rating: 4.5,
        price: "$24.99",
        priceWas: "",
        color: "Gold",
        aosDelay: 1200,
      },
      {
        id: "13",
        title: "Leather Belt",
        description: "High-quality leather belt for a sophisticated look.",
        img: "/images/accessories/leather-belt1.jpg",
        category: "Accessories",
        rating: 4.6,
        price: "$29.99",
        priceWas: "$39.99",
        color: "Brown",
        aosDelay: 1300,
      },
      {
        id: "14",
        title: "Polarized Sunglasses",
        description: "Protect your eyes with stylish polarized sunglasses.",
        img: "/images/accessories/sunglasses.jpg",
        category: "Accessories",
        rating: 4.8,
        price: "$49.99",
        priceWas: "",
        color: "Black",
        aosDelay: 1400,
      },
      {
        id: "15",
        title: "Summer Dress",
        description: "Light and airy summer dress for warm days.",
        img: "/images/men-clothing/t-shirts-1 (3).png",
        category: "Women's Clothing",
        rating: 4.7,
        price: "$34.99",
        priceWas: "$39.99",
        color: "Yellow",
        aosDelay: 1500,
      },
      {
        id: "16",
        title: "Sneakers",
        description: "Comfortable sneakers for everyday use.",
        img: "/images/shoes/running-1.jpg",
        category: "Footwear",
        rating: 4.6,
        price: "$59.99",
        priceWas: "",
        color: "White",
        aosDelay: 1600,
      },
      {
        id: "17",
        title: "Running Shoes",
        description: "Lightweight running shoes for active lifestyles.",
        img: "/images/shoes/running2.jpg",
        category: "Footwear",
        rating: 4.8,
        price: "$69.99",
        priceWas: "$79.99",
        color: "Blue",
        aosDelay: 1700,
      },
      {
        id: "18",
        title: "Classic Wallet",
        description: "Minimalistic wallet made of genuine leather.",
        img: "/images/accessories/wallet2.jpg",
        category: "Accessories",
        rating: 4.6,
        price: "$19.99",
        priceWas: "$24.99",
        color: "Brown",
        aosDelay: 1800,
      },
      {
        id: "19",
        title: "Hoodie",
        description: "Cozy hoodie for chilly days.",
        img: "/images/hoodie/hoodie1.jpg",
        category: "Men's Clothing",
        rating: 4.7,
        price: "$39.99",
        priceWas: "",
        color: "Gray",
        aosDelay: 1900,
      },
      {
        id: "20",
        title: "Formal Shoes",
        description: "Elegant formal shoes for office wear.",
        img: "/images/shoes/formal-shoe.jpg",
        category: "Footwear",
        rating: 4.9,
        price: "$89.99",
        priceWas: "$99.99",
        color: "Black",
        aosDelay: 2000,
      },
  ];
  
  // Categorizing data

  
// New Arrivals
export const NewArrivals = ProductsData.filter(product => !product.priceWas);

// Top Selling (criteria: rating > 4.7)
export const TopSell = ProductsData.filter(product => product.rating > 4.7);

// Products You May Like (criteria: rating > 4.5 && priceWas is not empty)
export const ProductsYouMayLike = ProductsData.filter(
  product => product.rating > 4.5 && product.priceWas
);