import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "../components/Navbar/Navbar";
import { Navbarbottom } from "../components/Navbar/Navbarbottom";
import "slick-carousel/slick/slick.css";  // Import Slick carousel styles
import "slick-carousel/slick/slick-theme.css";  // Import Slick carousel theme styles
import { Footer } from "@/components/Footer/Footer";
import { poppins } from "./fonts/fonts";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.className} antialiased`}
      >
        <Navbar/>
        <Navbarbottom/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
