// data/products.js

export const ProductsData = [
    {
      id: 1,
      img: "/images/men-clothing/t-shirts-2 (2).png",
      title: "Casual Wear",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "$120",
      rating: 4.5,
      category: "T-Shirts",
      color: "Blue",
      aosDelay: "0",
    },
    {
      id: 2,
      img: "/images/men-clothing/t-shirts-1 (2).png",
      title: "Printed shirt",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "$100",
      rating: 4.0,
      category: "Shirts",
      color: "Red",
      aosDelay: "200",
    },
    {
      id: 3,
      img: "/images/men-clothing/t-shirts-1 (4).png",
      title: "Women shirt",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "$150",
      rating: 4.8,
      category: "Women Shirts",
      color: "White",
      aosDelay: "400",
    },
    {
      id: 4,
      img: "/images/women-watches/watch-1-(2).jpg",
      title: "Women Ethnic Watch",
      description: "Beautiful ethnic watch for women.",
      price: "$200",
      rating: 5.0,
      category: "Watches",
      color: "Gold",
      aosDelay: "600",
    },
    {
      id: 5,
      img: "/images/men-watches/watch-3-(2).jpg",
      title: "Men's Classic Watch",
      description: "Classic watch for men with leather strap.",
      price: "$180",
      rating: 4.7,
      category: "Watches",
      color: "Brown",
      aosDelay: "800",
    },
    // New Products
    {
      id: 6,
      img: "/images/women-watches/watch-2-(2).jpg",
      title: "Women Ethnic",
      description: "Beautiful ethnic watch for women.",
      price: "$220",
      rating: 5.0,
      category: "Watches",
      color: "White",
      aosDelay: "1000",
    },
    {
      id: 7,
      img: "/images/women-watches/watch-3-(2).jpg",
      title: "Women Western",
      description: "Elegant western watch for women.",
      price: "$210",
      rating: 4.5,
      category: "Watches",
      color: "Red",
      aosDelay: "1200",
    },
    {
      id: 8,
      img: "/images/men-watches/watch-2-(2).jpg",
      title: "Watches",
      description: "Stylish watch for men with a modern design.",
      price: "$250",
      rating: 4.7,
      category: "Watches",
      color: "Brown",
      aosDelay: "1400",
    },
    {
      id: 9,
      img: "/images/men-clothing/denim-bottom (2).png",
      title: "Denim Bottom",
      description: "Comfortable denim bottoms for all occasions.",
      price: "$90",
      rating: 4.4,
      category: "Denim",
      color: "Blue",
      aosDelay: "1600",
    },
    {
      id: 10,
      img: "/images/men-clothing/t-shirts-2 (3).png",
      title: "Fashion T-Shirt",
      description: "Trendy T-shirt with a unique design.",
      price: "$80",
      rating: 4.5,
      category: "T-Shirts",
      color: "Pink",
      aosDelay: "1800",
    },
    {
      id: 11,
      img: "/images/men-watches/watch-1-(1).jpg",
      title: "Men Watch",
      description: "High-quality men’s watch with stainless steel band.",
      price: "$300",
      rating: 4.5,
      category: "Watches",
      color: "Pink",
      aosDelay: "2000",
    },
  ];
  
  export const TopSellData = [
    {
      id: 12,
      img: "/images/women-watches/watch-2-(2).jpg",
      title: "Women Ethnic",
      description: "Beautiful ethnic watch for women.",
      price: "$220",
      rating: 5.0,
      category: "Watches",
      color: "White",
      aosDelay: "0",
    },
    {
      id: 13,
      img: "/images/women-watches/watch-3-(2).jpg",
      title: "Women Western",
      description: "Elegant western watch for women.",
      price: "$210",
      rating: 4.5,
      category: "Watches",
      color: "Red",
      aosDelay: "200",
    },
    {
      id: 14,
      img: "/images/men-watches/watch-2-(2).jpg",
      title: "Watches",
      description: "Stylish watch for men with a modern design.",
      price: "$250",
      rating: 4.7,
      category: "Watches",
      color: "Brown",
      aosDelay: "400",
    },
    {
      id: 15,
      img: "/images/men-clothing/denim-bottom (2).png",
      title: "Denim Bottom",
      description: "Comfortable denim bottoms for all occasions.",
      price: "$90",
      rating: 4.4,
      category: "Denim",
      color: "Blue",
      aosDelay: "600",
    },
    {
      id: 16,
      img: "/images/men-clothing/t-shirts-2 (3).png",
      title: "Fashion T-Shirt",
      description: "Trendy T-shirt with a unique design.",
      price: "$80",
      rating: 4.5,
      category: "T-Shirts",
      color: "Pink",
      aosDelay: "800",
    },
  ];
  